"use client";
/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-img-element */

import Link from "next/link";
import { TeacherPlatformPage, TeacherPlatformHeader } from "@/components/platform/teacher-shell";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { BookOpen, ChevronDown, LockKeyhole, MoreHorizontal, ArrowUpRight, Plus, Settings2, UnlockKeyhole } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { offeringStatusLabel, instanceStatusLabel } from "@/lib/platform/labels";
import { teacherPlatformFetch } from "@/lib/platform/client";

import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { publishedClassroomVersion, teacherClassroomEntry } from "@/lib/platform/classroom-entry";

type Instance = { id: string; status: string };
type Activity = { id: string; title: string; type: string; isOpen: boolean; description?: string; version?: number; templateId?: string | null; config?: { content?: string; url?: string; questions?: Array<{ id: string; title: string; required: boolean }> }; instances?: Instance[] };
type Chapter = { id: string; title: string; isOpen: boolean; version?: number; activities: Activity[] };
type Offering = { id: string; name: string; term?: string | null; description?: string | null; coverImageUrl?: string | null; startsAt?: string | null; endsAt?: string | null; outline?: string; referenceMaterials?: string; status: string; version?: number; invitation?: { code: string } | null; chapters: Chapter[] };
type Template = { id: string; title: string; versions: Array<{ id: string; version: number; status: string }> };
const types: Record<string, string> = { Classroom: "课堂", Form: "问卷", Assignment: "作业", Quiz: "测验", Resource: "资料" };
const field = "min-h-11 w-full rounded-[6px] border border-[var(--pbl-border)] bg-[var(--pbl-surface)] px-3 py-2 text-sm";
const button = "inline-flex min-h-11 items-center justify-center gap-2 rounded-[6px] border border-[var(--pbl-border)] px-3 text-sm disabled:opacity-50";
const readyVersion = (template?: Template) => publishedClassroomVersion(template?.versions);

export default function TeacherClassEditorPage() {
  const router = useRouter();
  const { offeringId } = useParams<{ offeringId: string }>();
  const [offering, setOffering] = useState<Offering | null>(null);
  const [templates, setTemplates] = useState<Template[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [tab, setTab] = useState("chapters");
  const [dialog, setDialog] = useState<"chapter" | "activity" | "info" | null>(null);
  const [chapterId, setChapterId] = useState("");
  const [chapterTitle, setChapterTitle] = useState("");
  const [editChapter, setEditChapter] = useState<Chapter | null>(null);
  const [editActivity, setEditActivity] = useState<Activity | null>(null);
  const [activity, setActivity] = useState({ title: "", type: "Classroom", templateId: "", content: "", url: "", questions: "" });
  const [info, setInfo] = useState({ name: "", term: "", description: "", coverImageUrl: "", startsAt: "", endsAt: "", outline: "", referenceMaterials: "" });
  const load = useCallback(async () => {
    const [response, templateResponse] = await Promise.all([teacherPlatformFetch("/api/platform/offerings", { cache: "no-store" }), teacherPlatformFetch("/api/platform/templates", { cache: "no-store" })]);
    const [data, templateData] = await Promise.all([response.json(), templateResponse.json()]);
    if (!response.ok) throw new Error(data.message ?? "无法加载课程系列");
    const found = data.offerings?.find((item: Offering) => item.id === offeringId);
    if (!found) throw new Error("课程不存在或您没有访问权限");
    setOffering(found);
    if (!templateResponse.ok) throw new Error(templateData.message ?? "课程库暂时无法加载");
    setTemplates(templateData.templates ?? []);
  }, [offeringId]);
  useEffect(() => { void load().catch((reason) => setError(reason instanceof Error ? reason.message : "加载失败")); }, [load]);
  async function mutate(url: string, body?: unknown, method = "PATCH") {
    const response = await teacherPlatformFetch(url, { method, headers: { "Content-Type": "application/json" }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) });
    const data = await response.json(); if (!response.ok) throw new Error(data.message ?? "操作失败，请重试"); return data;
  }
  async function run(action: () => Promise<void>, success = "已保存") {
    if (busy) return; setBusy(true); setError(null); setMessage("");
    try { await action(); await load(); setMessage(success); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "操作失败，请重试"); }
    finally { setBusy(false); }
  }
  function openActivity(chapter: Chapter, item?: Activity) {
    setChapterId(chapter.id); setEditActivity(item ?? null); setError(null);
    setActivity({ title: item?.title ?? "", type: item?.type ?? "Classroom", templateId: item?.templateId ?? "", content: item?.config?.content ?? item?.description ?? "", url: item?.config?.url ?? "", questions: item?.config?.questions?.map((question) => question.title).join("\n") ?? "" }); setDialog("activity");
  }
  function openInfo() {
    if (!offering) return;
    setInfo({ name: offering.name, term: offering.term ?? "", description: offering.description ?? "", coverImageUrl: offering.coverImageUrl ?? "", startsAt: offering.startsAt?.slice(0, 10) ?? "", endsAt: offering.endsAt?.slice(0, 10) ?? "", outline: offering.outline ?? "", referenceMaterials: offering.referenceMaterials ?? "" }); setDialog("info"); setError(null);
  }
  function save(event: FormEvent) {
    event.preventDefault();
    void run(async () => {
      if (dialog === "chapter") await mutate(editChapter ? `/api/platform/chapters/${editChapter.id}` : `/api/platform/offerings/${offeringId}/chapters`, { title: chapterTitle.trim(), ...(editChapter ? { version: editChapter.version } : {}) }, editChapter ? "PATCH" : "POST");
      if (dialog === "info") await mutate(`/api/platform/offerings/${offeringId}`, { ...info, coverImageUrl: info.coverImageUrl || null, startsAt: info.startsAt ? new Date(`${info.startsAt}T00:00:00+08:00`).toISOString() : null, endsAt: info.endsAt ? new Date(`${info.endsAt}T23:59:59+08:00`).toISOString() : null, version: offering?.version });
      if (dialog === "activity") {
        const config = { schemaVersion: 1, content: activity.content, ...(activity.url ? { url: activity.url } : {}), ...(["Form", "Quiz"].includes(activity.type) ? { questions: activity.questions.split("\n").map((title) => title.trim()).filter(Boolean).map((title, index) => ({ id: editActivity?.config?.questions?.[index]?.id ?? `q${index + 1}`, title, required: true })) } : {}) };
        await mutate(editActivity ? `/api/platform/activities/${editActivity.id}/manage` : `/api/platform/offerings/${offeringId}/chapters/${chapterId}/activities`, { title: activity.title.trim(), description: activity.content, config, ...(editActivity ? { version: editActivity.version } : { type: activity.type }), ...(activity.type === "Classroom" ? { templateId: activity.templateId || undefined } : {}) }, editActivity ? "PATCH" : "POST");
      }
      setDialog(null);
    });
  }
  if (!offering) return <TeacherPlatformPage><TeacherPlatformHeader active="classes" /><div className="pbl-workspace-content"><Link href="/teacher/classes" className="text-sm">← 课程系列</Link><p role={error ? "alert" : "status"} className="mt-8">{error || "正在加载课程…"}</p>{error ? <button className={button} onClick={() => void run(async () => {})}>重试</button> : null}</div></TeacherPlatformPage>;
  const count = offering.chapters.reduce((total, chapter) => total + chapter.activities.length, 0);
  return <TeacherPlatformPage><TeacherPlatformHeader active="classes" leading={<><Link href="/teacher/classes">课程系列</Link><span>/</span><span className="truncate">课程管理</span></>} />

    <div className="pbl-workspace-content"><div className="pbl-course-heading flex flex-wrap items-start justify-between gap-6"><div className="max-w-3xl"><p className="text-xs tracking-wider text-[var(--pbl-text-muted)]">{offering.term || "课程系列"} · {offeringStatusLabel(offering.status)}</p><h1 className="mt-3 font-serif text-3xl font-semibold md:text-4xl">{offering.name}</h1><p className="mt-4 text-sm leading-7 text-[var(--pbl-text-muted)]">{offering.description || "以章节组织学习，将课堂与任务串成完整的课程。"}</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-[var(--pbl-text-muted)]"><span>{offering.chapters.length} 个章节 · {count} 项学习内容</span><span>{offering.startsAt ? `${new Date(offering.startsAt).toLocaleDateString("zh-CN")} 开课` : "开课日期待设置"}</span>{offering.invitation ? <span>学生邀请码 <strong className="ml-1 tracking-widest text-[var(--pbl-text)]">{offering.invitation.code}</strong>{offering.status.toLowerCase() === "draft" ? " · 可注册，内容待开放" : " · 已激活"}</span> : null}</div></div><div className="flex flex-wrap gap-2"><Link className={button} href={`/teacher/classes/${offeringId}/students`}>学生管理</Link>{!offering.invitation ? <button disabled={busy} className={button} onClick={() => void run(async () => { await mutate(`/api/platform/offerings/${offeringId}/invitation`, {}, "POST"); }, "学生邀请码已激活，可用于注册")}>激活学生邀请码</button> : null}{offering.status.toLowerCase() === "draft" ? <button disabled={busy} className={`${button} border-transparent bg-[var(--pbl-teacher)] text-white`} onClick={() => void run(async () => { await mutate(`/api/platform/offerings/${offeringId}`, { status: "open", version: offering.version }); }, "课程已开放，学生现在可以进入已解锁内容")}>开放课程</button> : null}<button className={button} onClick={openInfo}><Settings2 size={16} />课程设置</button></div></div>
      <div className="mt-9 flex items-center justify-between gap-4 border-b border-[var(--pbl-border)]"><div role="tablist" aria-label="课程管理" className="flex gap-7">{[["chapters", "章节目录"], ["overview", "课程主页"]].map(([value, label]) => <button key={value} role="tab" aria-selected={tab === value} className={`min-h-12 border-b-2 text-sm ${tab === value ? "border-[var(--pbl-teacher)] font-semibold text-[var(--pbl-teacher)]" : "border-transparent text-[var(--pbl-text-muted)]"}`} onClick={() => setTab(value)}>{label}</button>)}</div><p role="status" className="text-xs text-[var(--pbl-text-muted)]">{busy ? "正在保存…" : message}</p></div>
      {error && !dialog ? <p role="alert" className="mt-4 text-sm text-[var(--pbl-danger)]">{error}</p> : null}
      {tab === "chapters" ? <><div className="my-6 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-[var(--pbl-text-muted)]">在章节中添加学习内容；锁定章节后，学生可查看目录，暂不能进入。</p><button className={`${button} border-transparent bg-[var(--pbl-teacher)] text-white`} onClick={() => { setEditChapter(null); setChapterTitle(""); setError(null); setDialog("chapter"); }}><Plus size={16} />添加章节</button></div><div className="space-y-5">{offering.chapters.map((chapter, index) => <details open key={chapter.id} className="pbl-chapter-card overflow-hidden"><summary className="flex cursor-pointer list-none flex-wrap items-center gap-4 p-5 [&::-webkit-details-marker]:hidden"><span className="font-serif text-2xl text-[var(--pbl-text-muted)]">{String(index + 1).padStart(2, "0")}</span><h2 className="min-w-40 flex-1 font-serif text-lg font-semibold">{chapter.title}</h2><span className="text-xs text-[var(--pbl-text-muted)]">{chapter.activities.length} 项内容 · {chapter.isOpen ? "已解锁" : "已锁定"}</span><ChevronDown size={17} /></summary><div className="border-t border-[var(--pbl-border)]"><div className="flex flex-wrap items-center gap-2 bg-[var(--pbl-bg)]/50 px-5 py-2"><button className={`${button} border-transparent text-xs`} disabled={busy} onClick={() => void run(async () => { await mutate(`/api/platform/chapters/${chapter.id}`, { isOpen: !chapter.isOpen, version: chapter.version }); }, chapter.isOpen ? "章节已锁定" : "章节已解锁")}>{chapter.isOpen ? <LockKeyhole size={14} /> : <UnlockKeyhole size={14} />}{chapter.isOpen ? "锁定章节" : "解锁章节"}</button><button className={`${button} border-transparent text-xs`} onClick={() => { setEditChapter(chapter); setChapterTitle(chapter.title); setError(null); setDialog("chapter"); }}>编辑章节名称</button></div>{chapter.activities.map((item, itemIndex) => {
        const instance = item.instances?.[0];
        const template = templates.find((entry) => entry.id === item.templateId);
        const entry = instance ? teacherClassroomEntry(instance) : null;
        const version = readyVersion(template);
        return <div key={item.id} className="pbl-activity-row flex flex-wrap items-center gap-3 border-t border-[var(--pbl-border)] px-5 py-4 md:pl-14">
          <span className="w-8 text-xs tabular-nums text-[var(--pbl-text-muted)]">{index + 1}.{itemIndex + 1}</span>
          <span className="pbl-activity-kind rounded-[6px] border border-[var(--pbl-border)] px-2 py-1 text-xs text-[var(--pbl-text-muted)]">{types[item.type] || item.type}</span>
          <div className="min-w-40 flex-1"><p className="text-sm font-medium">{item.title}</p>{item.type === "Classroom" ? <p className="mt-1 text-xs text-[var(--pbl-text-muted)]">{template?.title || "待选择课程库课堂"}{instance ? ` · ${instanceStatusLabel(instance.status)}` : ""}{!instance && !version ? " · 请先在课程库发布教案" : ""}</p> : null}</div>
          {item.type === "Classroom" ? entry ? <Link className={`${button} pbl-classroom-entry text-xs text-[var(--pbl-teacher)]`} href={entry.href}>{entry.label}<ArrowUpRight size={14} /></Link> : version ? <button className={`${button} pbl-classroom-entry text-xs text-[var(--pbl-teacher)]`} disabled={busy} onClick={() => void run(async () => { const data = await mutate(`/api/platform/activities/${item.id}/instance`, { templateVersionId: version.id }, "POST"); if (!data.instance?.id) throw new Error("课堂创建失败，请重试"); router.push(teacherClassroomEntry(data.instance).href); })}>进入课堂<ArrowUpRight size={14} /></button> : <Link className={`${button} text-xs`} href="/teacher/templates">前往课程库</Link> : <button className={`${button} text-xs`} onClick={() => openActivity(chapter, item)}>编辑内容</button>}
          <DropdownMenu><DropdownMenuTrigger asChild><button className={`${button} border-transparent text-xs`} aria-label={`${item.title}更多操作`} disabled={busy}><MoreHorizontal size={18} /><span className="sr-only">更多</span></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="pbl-platform-theme pbl-platform-dialog"><DropdownMenuItem onSelect={() => openActivity(chapter, item)}>编辑名称与内容关联</DropdownMenuItem><DropdownMenuItem onSelect={() => void run(async () => { await mutate(`/api/platform/activities/${item.id}/manage`, { isOpen: !item.isOpen, version: item.version }); }, item.isOpen ? "内容已锁定" : "内容已解锁")}>{item.isOpen ? "锁定内容" : "解锁内容"}</DropdownMenuItem>{instance && instance.status !== "finished" ? <DropdownMenuItem asChild><Link href={`/teacher/classrooms/${instance.id}`}>课堂学习记录</Link></DropdownMenuItem> : null}</DropdownMenuContent></DropdownMenu>
        </div>;
      })}{chapter.activities.length === 0 ? <p className="px-5 py-6 text-sm text-[var(--pbl-text-muted)] md:pl-14">本章还没有内容。可以从课程库选择课堂，或添加其他学习任务。</p> : null}<button className="flex min-h-14 w-full items-center gap-2 border-t border-dashed border-[var(--pbl-border)] px-5 text-sm text-[var(--pbl-teacher)] md:pl-14" onClick={() => openActivity(chapter)}><Plus size={16} />添加学习内容</button></div></details>)}</div>{offering.chapters.length === 0 ? <div className="rounded-[10px] border border-dashed border-[var(--pbl-border)] px-6 py-16 text-center"><BookOpen size={32} strokeWidth={1} className="mx-auto text-[var(--pbl-text-muted)]" /><h2 className="mt-5 font-serif text-xl">建立课程的第一章</h2><p className="mt-3 text-sm text-[var(--pbl-text-muted)]">先确定学习阶段，再加入课堂、问卷、作业和资料。</p></div> : null}</> : <div className="mt-7 grid gap-8 md:grid-cols-[1fr_280px]"><div className="space-y-8">{offering.coverImageUrl ? <img src={offering.coverImageUrl} alt={`${offering.name}课程封面`} className="max-h-72 w-full rounded-[10px] object-cover" /> : null}{[["课程详情", offering.description], ["课程大纲", offering.outline], ["参考资料", offering.referenceMaterials]].map(([title, content]) => <section key={title} className="border-b border-[var(--pbl-border)] pb-8"><h2 className="font-serif text-xl font-semibold">{title}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-8 text-[var(--pbl-text-muted)]">{content || "尚未填写，可在课程设置中完善。"}</p></section>)}</div><aside className="self-start rounded-[10px] border border-[var(--pbl-border)] bg-[var(--pbl-surface)] p-5"><h2 className="font-semibold">课程开放</h2><p className="mt-3 text-sm leading-7 text-[var(--pbl-text-muted)]">开放课程后，已加入的学生可学习已解锁章节中的内容。</p><p className="mt-4 text-sm">当前：{offeringStatusLabel(offering.status)}</p><button disabled={busy} className={`${button} mt-5 w-full`} onClick={() => void run(async () => { await mutate(`/api/platform/offerings/${offeringId}`, { status: offering.status.toLowerCase() === "open" ? "finished" : "open", version: offering.version }); })}>{offering.status.toLowerCase() === "open" ? "结束本期课程" : "开放课程"}</button><button className={`${button} mt-3 w-full`} onClick={openInfo}>编辑课程主页</button></aside></div>}
    </div>
    <Dialog open={dialog !== null} onOpenChange={(value) => { if (!value && !busy) setDialog(null); }}><DialogContent className="pbl-platform-theme pbl-platform-dialog max-h-[90vh] overflow-y-auto bg-[var(--pbl-surface)] sm:max-w-2xl"><DialogHeader><DialogTitle className="font-serif text-2xl">{dialog === "info" ? "课程设置" : dialog === "chapter" ? editChapter ? "编辑章节" : "添加章节" : editActivity ? "编辑学习内容" : "添加学习内容"}</DialogTitle><DialogDescription>{dialog === "info" ? "这里的信息将展示在学生的课程主页。" : dialog === "chapter" ? "按照学习阶段组织章节，让课程路径清晰可循。" : `添加到：${offering.chapters.find((chapter) => chapter.id === chapterId)?.title ?? "当前章节"}`}</DialogDescription></DialogHeader><form className="space-y-5" onSubmit={save}>
      {dialog === "chapter" ? <label className="block space-y-2 text-sm"><span>章节名称</span><input autoFocus required maxLength={160} className={field} value={chapterTitle} onChange={(event) => setChapterTitle(event.target.value)} placeholder="例如：发现问题与实地调研" /></label> : null}
      {dialog === "activity" ? <><label className="block space-y-2 text-sm"><span>内容类型</span><select disabled={Boolean(editActivity)} className={field} value={activity.type} onChange={(event) => setActivity({ ...activity, type: event.target.value })}>{Object.entries(types).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block space-y-2 text-sm"><span>标题</span><input required maxLength={160} className={field} value={activity.title} onChange={(event) => setActivity({ ...activity, title: event.target.value })} /></label>{activity.type === "Classroom" ? <div className="space-y-2"><label className="text-sm" htmlFor="template">从课程库选择课堂</label><select id="template" required disabled={Boolean(editActivity?.instances?.[0] && editActivity.instances[0].status !== "finished")} className={field} value={activity.templateId} onChange={(event) => { const template = templates.find((item) => item.id === event.target.value); setActivity({ ...activity, templateId: event.target.value, title: activity.title || template?.title || "" }); }}><option value="">选择已就绪的课堂</option>{templates.filter((template) => readyVersion(template)).map((template) => <option key={template.id} value={template.id}>{template.title} · v{readyVersion(template)?.version}</option>)}</select><p className="text-xs leading-6 text-[var(--pbl-text-muted)]">在独立课程库中生成与备课，再应用到本章节。<Link className="ml-1 underline" href="/teacher/templates">前往课程库</Link></p></div> : <><label className="block space-y-2 text-sm"><span>{activity.type === "Assignment" ? "作业要求" : "内容说明"}</span><textarea className={`${field} min-h-28`} value={activity.content} onChange={(event) => setActivity({ ...activity, content: event.target.value })} /></label>{activity.type === "Resource" ? <label className="block space-y-2 text-sm"><span>资料链接（可选）</span><input type="url" pattern="https?://.*" placeholder="https://" className={field} value={activity.url} onChange={(event) => setActivity({ ...activity, url: event.target.value })} /></label> : null}{["Form", "Quiz"].includes(activity.type) ? <label className="block space-y-2 text-sm"><span>题目（每行一题，学生填写文字回答）</span><textarea required className={`${field} min-h-32`} value={activity.questions} onChange={(event) => setActivity({ ...activity, questions: event.target.value })} placeholder="你希望在本课程中解决什么问题？&#10;请分享你已有的相关经验。" /></label> : null}</>}</> : null}
      {dialog === "info" ? <><div className="grid gap-4 sm:grid-cols-2">{[["name", "课程名称"], ["term", "学期"], ["startsAt", "开课日期"], ["endsAt", "结课日期"]].map(([key, label]) => <label key={key} className="block space-y-2 text-sm"><span>{label}</span><input required={key === "name"} type={key.endsWith("At") ? "date" : "text"} className={field} value={info[key as keyof typeof info]} onChange={(event) => setInfo({ ...info, [key]: event.target.value })} /></label>)}</div><label className="block space-y-2 text-sm"><span>封面图片地址</span><input type="url" pattern="https?://.*" className={field} placeholder="https://…" value={info.coverImageUrl} onChange={(event) => setInfo({ ...info, coverImageUrl: event.target.value })} /></label>{[["description", "课程详情"], ["outline", "整体课程大纲"], ["referenceMaterials", "参考资料"]].map(([key, label]) => <label key={key} className="block space-y-2 text-sm"><span>{label}</span><textarea className={`${field} min-h-24`} value={info[key as keyof typeof info]} onChange={(event) => setInfo({ ...info, [key]: event.target.value })} /></label>)}</> : null}
      {error ? <p role="alert" className="text-sm text-[var(--pbl-danger)]">{error}</p> : null}<div className="flex justify-end gap-3 border-t border-[var(--pbl-border)] pt-4"><button type="button" disabled={busy} className={button} onClick={() => setDialog(null)}>取消</button><button disabled={busy} className={`${button} border-transparent bg-[var(--pbl-teacher)] px-6 text-white`}>{busy ? "保存中…" : "保存"}</button></div>
    </form></DialogContent></Dialog>
  </TeacherPlatformPage>;
}
