"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";

type Student = { id: string; username: string; displayName: string; progress: Array<{ status: string }> };
export default function TeacherStudentsPage() { const params = useParams<{ offeringId: string }>(); const [students, setStudents] = useState<Student[]>([]); const [message, setMessage] = useState<string | null>(null); useEffect(() => { fetch(`/api/platform/offerings/${params.offeringId}/students`, { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message ?? "无法加载学生"); setStudents(data.students.map((item: { user: Student; progress: Student["progress"] }) => ({ ...item.user, progress: item.progress }))); }).catch((error) => setMessage(error instanceof Error ? error.message : "加载失败")); }, [params.offeringId]); async function reset(enrollmentId: string) { const response = await fetch(`/api/platform/offerings/${params.offeringId}/reset-password`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enrollmentId }) }); const data = await response.json(); setMessage(response.ok ? `一次性重置链接：${location.origin}/student/reset-password?token=${data.token}` : data.message ?? "生成失败"); } return <main className="min-h-screen bg-[var(--pbl-bg)] px-5 py-10 text-[var(--pbl-text)]"><div className="mx-auto max-w-3xl"><Link href={`/teacher/classes/${params.offeringId}`} className="text-sm text-[var(--pbl-text-muted)]">← 返回课程编排</Link><h1 className="mt-6 text-3xl font-bold">学生名单</h1>{message ? <p className="mt-4 break-all rounded-lg bg-indigo-50 p-3 text-sm text-indigo-800">{message}</p> : null}<div className="mt-6 overflow-hidden rounded-xl border border-[var(--pbl-border)] bg-white">{students.map((student) => <div className="flex flex-wrap items-center gap-3 border-b border-[var(--pbl-border)] px-4 py-4 last:border-0" key={student.id}><div className="flex-1"><p className="font-semibold">{student.displayName}</p><p className="mt-1 text-xs text-[var(--pbl-text-muted)]">账号：{student.username} · 已完成 {student.progress.filter((item) => item.status === "completed").length} 项</p></div><button className="rounded-lg border border-[var(--pbl-border)] px-3 py-2 text-xs font-semibold" onClick={() => void reset(student.id)} type="button">生成密码重置链接</button></div>)}{students.length === 0 ? <p className="p-6 text-sm text-[var(--pbl-text-muted)]">暂时没有学生加入。</p> : null}</div></div></main>; }

