function uint32le(data: Uint8Array, offset: number): number {
  return data[offset]! | (data[offset + 1]! << 8) | (data[offset + 2]! << 16) | (data[offset + 3]! << 24 >>> 0);
}

function wavDurationSec(data: Uint8Array): number | undefined {
  if (data.length < 44 || new TextDecoder("ascii").decode(data.slice(0, 4)) !== "RIFF"
    || new TextDecoder("ascii").decode(data.slice(8, 12)) !== "WAVE") return undefined;
  let offset = 12;
  let byteRate = 0;
  let dataSize = 0;
  while (offset + 8 <= data.length) {
    const chunkId = new TextDecoder("ascii").decode(data.slice(offset, offset + 4));
    const chunkSize = uint32le(data, offset + 4) >>> 0;
    const body = offset + 8;
    if (chunkId === "fmt " && chunkSize >= 16 && body + 12 <= data.length) byteRate = uint32le(data, body + 8) >>> 0;
    if (chunkId === "data") {
      dataSize = Math.min(chunkSize, Math.max(0, data.length - body));
      break;
    }
    offset = body + chunkSize + (chunkSize % 2);
  }
  return byteRate > 0 && dataSize > 0 ? dataSize / byteRate : undefined;
}

const MPEG1_BITRATES = {
  1: [0, 32, 64, 96, 128, 160, 192, 224, 256, 288, 320, 352, 384, 416, 448],
  2: [0, 32, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320],
  3: [0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256],
} as const;
const MPEG2_BITRATES = {
  1: [0, 32, 48, 56, 64, 80, 96, 112, 128, 144, 160, 176, 192, 224],
  2: [0, 8, 16, 24, 32, 40, 48, 56, 64, 80, 96, 112, 128, 144],
  3: [0, 8, 16, 24, 32, 40, 48, 56, 64, 80, 96, 112, 128, 144],
} as const;

function synchsafe(data: Uint8Array, offset: number): number {
  return ((data[offset]! & 0x7f) << 21) | ((data[offset + 1]! & 0x7f) << 14)
    | ((data[offset + 2]! & 0x7f) << 7) | (data[offset + 3]! & 0x7f);
}

function mp3DurationSec(data: Uint8Array): number | undefined {
  let offset = data.length >= 10 && String.fromCharCode(...data.slice(0, 3)) === "ID3"
    ? 10 + synchsafe(data, 6)
    : 0;
  let duration = 0;
  let frames = 0;
  while (offset + 4 <= data.length) {
    const header = ((data[offset]! << 24) | (data[offset + 1]! << 16) | (data[offset + 2]! << 8) | data[offset + 3]!) >>> 0;
    if (((header & 0xffe00000) >>> 0) !== 0xffe00000) {
      if (frames > 0) break;
      offset += 1;
      continue;
    }
    const versionBits = (header >>> 19) & 0x3;
    const layerBits = (header >>> 17) & 0x3;
    const bitrateIndex = (header >>> 12) & 0xf;
    const sampleRateIndex = (header >>> 10) & 0x3;
    const padding = (header >>> 9) & 0x1;
    if (versionBits === 1 || layerBits === 0 || bitrateIndex === 0 || bitrateIndex === 15 || sampleRateIndex === 3) {
      if (frames > 0) break;
      offset += 1;
      continue;
    }
    const version = versionBits === 3 ? 1 : versionBits === 2 ? 2 : 2.5;
    const layer = layerBits === 3 ? 1 : layerBits === 2 ? 2 : 3;
    const table = version === 1 ? MPEG1_BITRATES : MPEG2_BITRATES;
    const bitrateKbps = table[layer][bitrateIndex];
    const baseRate = [44_100, 48_000, 32_000][sampleRateIndex]!;
    const sampleRate = version === 1 ? baseRate : version === 2 ? baseRate / 2 : baseRate / 4;
    const samplesPerFrame = layer === 1 ? 384 : layer === 2 || version === 1 ? 1_152 : 576;
    const frameLength = layer === 1
      ? Math.floor(12 * bitrateKbps * 1_000 / sampleRate + padding) * 4
      : Math.floor((layer === 3 && version !== 1 ? 72 : 144) * bitrateKbps * 1_000 / sampleRate + padding);
    if (!frameLength || offset + frameLength > data.length) break;
    duration += samplesPerFrame / sampleRate;
    frames += 1;
    offset += frameLength;
  }
  return frames > 0 ? duration : undefined;
}

/** Decode duration from the generated bytes without changing playback or speech speed. */
export function audioDurationSec(data: Uint8Array, format: string): number | undefined {
  const normalized = format.toLowerCase().replace(/^audio\//, "").split(/[;.]/, 1)[0];
  const duration = normalized === "wav" || normalized === "wave" || normalized === "x-wav"
    ? wavDurationSec(data)
    : normalized === "mp3" || normalized === "mpeg"
      ? mp3DurationSec(data)
      : undefined;
  return duration && Number.isFinite(duration) && duration > 0
    ? Math.round(duration * 1_000) / 1_000
    : undefined;
}
