import type { SceneOutline } from './outline-types.js';
import { resolveDiagramSequenceGroups, type DiagramAllocation } from './diagram-compiler.js';
import type { AuthoringContentItem, AuthoringTextAllocation } from './authoring-content.js';

function adoptedContentContract(contract: { system: string; user: string }, content: readonly AuthoringContentItem[] | undefined,
  mode: 'native' | 'flow', textAllocations?: readonly AuthoringTextAllocation[]) {
  if (!content?.length) return contract;
  const ids = content.map((item) => item.id);
  const required = content.filter((item) => item.required !== false).map((item) => item.id);
  const exampleIds = (required.length ? required : ids).slice(0, 2);
  const exampleId = exampleIds[0]!;
  const examples = mode === 'native' ? {
    textBox: { kind: 'textBox', id: 'authored-point', left: 60, top: 140, width: 880,
      role: 'body', fontSize: 24, paragraphRefs: exampleIds },
    richText: { type: 'text', id: 'authored-rich-point', left: 60, top: 140, width: 880, height: 110,
      contentRef: exampleId, content: '<p style="font-size:24px;color:#263445"><strong></strong></p>' },
    tableCell: { id: 'authored-cell', contentRef: exampleId, rowspan: 1, colspan: 1, style: { fontsize: 22 } },
    labelGrid: { kind: 'labelGrid', id: 'authored-grid', left: 60, top: 140, width: 880, height: 160, fontSize: 22,
      rows: exampleIds.map((contentRef) => ({ cells: [{ contentRef }] })) },
  } : {
    textBox: { kind: 'textBox', role: 'body', fontSize: 24, paragraphRefs: exampleIds },
    labelGrid: { kind: 'labelGrid', fontSize: 22,
      rows: exampleIds.map((contentRef) => ({ cells: [{ contentRef }] })) },
  };
  const slots = mode === 'native'
    ? 'textBox components, native elements with type:"text", native table DATA CELLS, and labelGrid headers/cells. On native table cells, contentRef/paragraphRefs are siblings of id, text and style, not properties on the row or table. Native text may keep an empty enclosing HTML content value for its intended rich typography; the compiler supplies its visible prose.'
    : 'textBox blocks and labelGrid headers/cells inside layout.groups (including row/column children). Return flow blocks without coordinates or native text/table elements; flow native blocks only support charts and formulae.';
  return {
    system: `${contract.system}\n\n## Authoritative adopted presentation-point slots\nThe catalog below is the FINAL selected display content for THIS page. These points have already been condensed from the original source. Original source passages and narration serve as evidence and spoken explanation; do not perform another summarization of the catalog or recreate the whole section on this page. These slot rules extend ${mode === 'native' ? 'the earlier native JSON schema' : 'the permitted text blocks inside layout.groups'} and take precedence over instructions to shorten or rewrite text. Keep ${mode === 'native' ? 'native visual composition, learner-facing headings and rich typography' : 'semantic flow grouping and the compiler-owned page title/geometry'}, and every required planned diagram/media resource. You own grouping and ${mode === 'native' ? 'layout' : 'representation'}; the host owns the adopted point text.\nUse contentRef:"exact-catalog-id" for one point or paragraphRefs:["first-id","second-id"] for separate complete paragraphs. These are actual JSON PROPERTIES on display slots, not strings to render inside content/text/paragraphs and not top-level planning metadata. Supported slots: ${slots} In labelGrid, rows is a NONEMPTY ARRAY of objects; EACH row needs cells:[...], every row has the SAME positive number of cells, and every cell is a nonempty literal label or a reference object. Either OMIT header in EVERY row or supply a nonempty literal/reference header in EVERY row. Never create a sparse grid, an empty placeholder cell or a row with only header/contentRef. Choose ordinary text regions when the ideas have no genuine aligned dimensions.\nThe compiler inserts the exact point text BEFORE measuring it with the playback font. There is no missing-point insertion afterward. Include EVERY required id in a supported visible slot in this FIRST response; required defaults to true. Metadata or narration cannot satisfy a display duty. Unknown ids, misplaced refs, missing points, unequal grid rows and unreadable allocations will reject the response. Explicit sequence groups retain their index order. Page-local adopted points determine the scope of an older whole-section representation preference. Retain accurate meaning, conditions and relationships in these already adopted points while choosing a fitting representation.`,
    user: `${contract.user}\n\nImmutable adopted presentation-point catalog (references apply only to this page): ${JSON.stringify(content)}\nRequired display-reference ids (${required.length}): ${JSON.stringify(required)}\nAccepted reference-slot JSON examples: ${JSON.stringify(examples)}\nExamples illustrate individual slot syntax, not a page template or required relationship. Choose suitable composition and actual measured space for the full supplied text; ${mode === 'native' ? 'native geometry remains authored' : 'flow blocks have no coordinates or authored rectangles'}. Use every required id across your chosen slots, with no invented catalog ids. Check the final response against the required-id list before returning it.${mode === 'native' && textAllocations ? `\nMeasured adopted-point native text-space candidates: ${JSON.stringify(textAllocations)}\nThese are complete single-point measurements at the stated font size/outer width, using playback Noto Sans SC, normal weight, 10px padding on EACH side, 1.5 line height and 5px paragraph spacing. The measured height includes the full text and padding. Only successful readable measurements are listed; an absent choice is not a zero-height or feasible rectangle. For a matching plain native region use at least its full measured height. Rich/mixed/bold typography still needs its actual space; retain rich emphasis and measure it through the native compiler. For paragraphRefs spanning several points, reserve the COMBINED paragraphs' height, not the tallest single-point choice. Plain multi-point textBox components can receive measured heights automatically. The original height lookup table is not authoritative for different real fonts, wrapped lines or referenced content. Keep surrounding cards, diagrams and text clear of the measured region.` : ''}`,
  };
}

function authoritativeDiagram(outline: SceneOutline) {
  const plan = outline.visualIntent?.diagram;
  if (!plan) return undefined;
  const sequenceGroups = resolveDiagramSequenceGroups(plan);
  return sequenceGroups ? { ...plan, sequenceGroups } : plan;
}

/** The model owns meaning and grouping; the first-pass compiler owns geometry. */
export function flowAuthoringContract(outline: SceneOutline, authoringContent?: readonly AuthoringContentItem[]): { system: string; user: string } {
  const diagram = authoritativeDiagram(outline);
  return adoptedContentContract({
    system: `# First-draft component authoring
You design an educational slide. Return pure JSON: {"background":{"type":"solid","color":"#ffffff"},"layout":{"groups":[]}}. The compiler supplies the exact page title, measures text with the playback font, tries a wider and tighter single-page arrangement, then creates at most one continuation page if needed. More than two measured pages is a section-planning error. Do not output elements, coordinates, widths, heights, or a title block. There is no later AI layout review.

Plan the whole lesson as a sequence of small, coherent teaching units before deciding where a page may break. Each top-level group must stay together on one page. Keep a definition, worked example, comparison or picture with its short observation together; place separate explanations in their own groups. Give successive units distinct teaching roles so continuation pages advance the explanation instead of repeating the first page or moving only a leftover paragraph. The compiler chooses balanced page breaks from all measured groups. Never put the entire lesson in one giant group. Preserve complete core definitions, conditions and conclusions; put spoken reasoning in narration. Do not split a definition across groups or discard content to fit.

Allowed blocks:
- Editable text: {"kind":"textBox","role":"body|label","text":"complete statement","fontSize":24,"bold":false,"color":"#263445"}. Use paragraphs:["first statement","second statement"] instead of text for distinct paragraphs. Body 22–28px, short label 18–22px. Hard newlines only at meaningful semantic boundaries; never manually break a short label into characters.
- Aligned comparison: {"kind":"labelGrid","rows":[{"header":"Dimension","cells":["First object","Second object"]}],"fontSize":20}. Equal cell counts per row. Use for genuine common comparison dimensions. The compiler balances wrapping and column widths.
- Visual relationship: {"kind":"diagram","topology":"sequence|cycle|branch","nodes":[{"id":"step-1","label":"step name"},{"id":"step-2","label":"step name"}],"edges":[],"annotation":"independent explanation"}. When a planned diagram is supplied, include exactly one diagram block; the compiler preserves that plan's exact nodes, order, edges and annotation. A sequence connects adjacent steps and may add at most one backward feedback edge. Parallel sequenceGroups are independent ordered chains inside that one diagram block: never split them into multiple diagram blocks or connect one group's last node to the next group's first node. A cycle has a complete directed ring. A branch expresses choices, forks or merges: give every directed edge explicitly, with one root, no cycles and all nodes reachable from the root; sibling options are not successive steps. Annotation is never an extra step. Node names must be concise; explain their meaning in separate text groups.
- Media: {"kind":"media","resourceId":"exact provided ID","mediaType":"image|video","aspectRatio":"16:9|4:3|1:1|9:16","observation":"what students should observe"}. Every required media resource must appear where it supports observation. Use the supplied aspect ratio. The compiler reserves its space before laying out text. Never invent resource IDs, URLs or decorative images.
- Precise chart or formula: {"kind":"native","element":{"type":"chart","chartType":"bar","data":{"labels":["A","B"],"legends":["Value"],"series":[[1,2]]}}}, or {"kind":"native","element":{"type":"latex","latex":"x^2"}}. Use actual supplied numeric data only. Native chart/formula geometry is reserved by the compiler; all accompanying explanation uses text blocks.
- Group: {"kind":"row|column","id":"stable-semantic-name","children":[blocks],"weights":[1,1],"keepTogether":true}. Rows arrange related items side by side; columns stack them. Optional positive weights control relative row widths. Keep a picture with its necessary observation, both sides of a comparison, and a definition with its conditions in the same row; rows stay together across page breaks. Use keepTogether for any column that must remain intact. Put independent explanations in separate groups. The compiler can stack an infeasibly narrow row.

Choose representations from what students need to understand, without a required number of pictures or template quota. Respect the planned representation and its rationale. Definitions and parallel principles use text or grouped explanations; common comparison dimensions use aligned rows or tables; ordinary ordered steps can use a numbered list. Use a node-and-arrow diagram when reading its dependencies, branches, feedback or cycle helps understanding. Concept levels are not chronological steps. Images show observable objects and situations; labels and exact relationships stay editable. Continuation pages retain the same blue title hierarchy, editable content and semantic grouping. Avoid duplicate text that merely repeats every diagram node. Return a viable semantic design in this single response.`,
    user: diagram
      ? `Return the flow-layout JSON. Include exactly one diagram block for this authoritative relationship: ${JSON.stringify(diagram)}. All independent sequenceGroups stay inside that one block.`
      : 'Return the flow-layout JSON. Select text, numbered steps, comparisons, media or a relationship diagram according to the planned teaching purpose and rationale.',
  }, authoringContent, 'flow');
}

/** Keep the native slide authoring vocabulary; compile only local components. */
export function componentAuthoringContract(outline: SceneOutline, diagramAllocations: DiagramAllocation[] = [],
  authoringContent?: readonly AuthoringContentItem[], textAllocations?: readonly AuthoringTextAllocation[]): { system: string; user: string } {
  const diagram = authoritativeDiagram(outline);
  const contract = adoptedContentContract({
    system: `## Optional first-draft measured components
Keep the complete native slide design: editable elements, shapes, tables, charts, rich text emphasis, borders, accent bars, pictures and the authored page hierarchy. Return {"background":...,"elements":[...],"components":[...]}. Components are optional local helpers; do not replace the page with a flow layout or split it into continuation pages. Preserve a coherent teaching page, with concise visible evidence and deeper spoken reasoning in narration.
Use the original typography and content-specific composition from the slide design instructions. All visible text is measured with the playback font. Prefer measured textBox components for plain titles, explanations and labels; use native text only when rich emphasis or mixed typography is needed. Native text has 10px padding on each side, so its usable width is 20px less than its rectangle. At the actual font size, leave enough width and height for every visible line and avoid a final line containing only one Chinese character or punctuation. Preserve semantic paragraph breaks and complete meaning. If a label cannot fit, give it more clear space or redesign its surrounding layout before returning JSON.
Optional text component: {"kind":"textBox","id":"stable-id","left":60,"top":140,"width":360,"height":90,"text":"a concise statement","fontSize":18,"bold":false,"color":"#334155","role":"body|label|title"}. Height is an estimate; the compiler uses the measured height and checks it against nearby foreground content and the slide boundary. Do not assign a guessed hard maxHeight to fit text. Use native text elements for mixed emphasis, colors, or font sizes.
Optional aligned label component: {"kind":"labelGrid","id":"stable-id","left":60,"top":140,"width":880,"height":200,"rows":[{"header":"dimension","cells":["first","second"]}],"fontSize":16}. Native tables remain available and preferred for genuine tables.
Planned relationship component: {"kind":"diagram","id":"stable-id","left":60,"top":140,"width":880,"height":330,"topology":"sequence|cycle|branch","nodes":[{"id":"a","label":"step"},{"id":"b","label":"next"}]}. The existing type:"diagram" discriminator is also accepted; never supply conflicting type and kind. Its rectangle and optional accentColor/nodeFill/textColor belong to your page design; the compiler supplies the exact planned nodes and edges. Sequence connects adjacent steps with at most one backward feedback edge; cycle closes the ordered ring. Parallel sequenceGroups stay inside this ONE components entry with kind:"diagram", each with its own ordered nodes and no cross-group arrows. Two parallel flows require one composite diagram, not two diagram components or separately authored native shapes. Branch keeps every explicit choice, fork or merge in one rooted, connected directed acyclic graph and never adds transitions between siblings. Reserve room for its annotation outside the diagram. Do not draw duplicate diagram nodes/connectors in native elements.
Arrows, connecting lines, aligned pairs and visual correspondence assert a real teaching relationship. Do not force introductory examples into a one-to-one mapping with concepts, or invent a correspondence, hierarchy or causal link not established by the supplied teaching design. If examples are only an introduction, present them as shared context without misleading connectors.
Respect the planned visual representation and its rationale. Definitions and parallel principles use text or grouped explanations; common comparison dimensions use tables; ordinary ordered steps can use a numbered list. Use node-and-arrow diagrams when students need to read dependencies, branches, feedback or a cycle. Concept levels are not chronological steps. Give a necessary diagram enough room for readable labels and balanced geometry, including a full-width region when a narrow sidebar cannot fit it. Its measured allocations already include the complete annotation; do not repeat that annotation as another text block.
Only an explicit diagram in THIS page's Visual Intent requires exactly one relationship component. A preferred text, table, chart or illustration form without that diagram has no relationship component quota. Continuation pages carry only their own assigned content and resources.
Components compile inside their allocated rectangles in this same first response. Background surfaces may deliberately contain their own foreground elements. Before returning JSON, check every pair of native teaching-text rectangles and every pair of peer content panels: they must occupy separate regions. In particular, a sidebar must not cover a neighboring card, its text, or another sidebar. Keep unrelated foreground content outside each component allocation. Include each required media resource as a native image/video in the page where it supports observation.`,
    user: diagram
      ? `Return native editable elements with exactly one local diagram component for this authoritative relationship: ${JSON.stringify(diagram)}\nAll independent sequenceGroups belong inside that ONE components entry with kind:"diagram" (type:"diagram" is also accepted). Measured feasible diagram rectangles (including node labels and the outside annotation): ${JSON.stringify(diagramAllocations)}. Choose one complete width/height pair or a rectangle at least as wide AND as high as one pair. A smaller arbitrary rectangle will not fit. You choose its left/top and the rest of the native page layout. Keep left >= 50, top >= 50, left+width <= 950 and top+height <= 512.5; reserve the page title and keep unrelated foreground content outside the chosen rectangle. The diagram is one local region, not the whole-page layout.`
      : 'Return native editable elements, with optional local text or label components only where helpful. Preserve the page composition and rich text styles.',
  }, authoringContent, 'native', textAllocations);
  if (!authoringContent?.length) return contract;
  const required = authoringContent.filter((item) => item.required !== false).map((item) => item.id);
  return { ...contract, user: `${contract.user}\n\n## Final first-response layout decisions\nRequired adopted display ids: ${JSON.stringify(required)}${diagram ? `\nAuthoritative diagram complete measured width/height PAIRS: ${JSON.stringify(diagramAllocations.map(({ width, height }) => ({ width, height })))}\nSelect ONE complete pair, or a rectangle at least as wide AND as high as the SAME pair. Never mix a smaller width from one pair with a smaller height from another. These pairs already include ALL canonical nodes, edges, labels and the complete annotation. Keep that annotation inside this diagram allocation contract, without silently dropping or duplicating it.` : ''}\nPlace every required adopted id in a real reference slot in this first response. Check actual font and full measured rectangle sizes before laying out neighboring rich text, native cards, tables, media and the planned relationship.` };
}
