import type { SceneOutline } from './outline-types.js';
import type { DiagramAllocation } from './diagram-compiler.js';

/** Native design contract restored from 4615a98d; current topology compilation remains authoritative. */
/** Keep the native slide authoring vocabulary; compile only local components. */
export function restoredComponentAuthoringContract(outline: SceneOutline, diagramAllocations: DiagramAllocation[] = []): { system: string; user: string } {
  return {
    system: `## Optional first-draft measured components
Keep the complete native slide design: editable elements, shapes, tables, charts, rich text emphasis, borders, accent bars, pictures and the authored page hierarchy. Return {"background":...,"elements":[...],"components":[...]}. Components are optional local helpers; do not replace the page with a flow layout or split it into continuation pages. Preserve a coherent teaching page, with concise visible evidence and deeper spoken reasoning in narration.
Use the original typography and content-specific composition from the slide design instructions. All visible text is measured with the playback font. Preserve semantic paragraph breaks; a short label must not leave a single Chinese character, including its punctuation, alone on a wrapped line. Allocate enough width and height at the chosen readable font size; do not omit meaning to fit.
Optional text component: {"kind":"textBox","id":"stable-id","left":60,"top":140,"width":360,"height":90,"text":"a concise statement","fontSize":18,"bold":false,"color":"#334155","role":"body|label|title"}. Height is an estimate; the compiler uses the measured height and checks it against nearby foreground content and the slide boundary. Do not assign a guessed hard maxHeight to fit text. Use native text elements for mixed emphasis, colors, or font sizes.
Optional aligned label component: {"kind":"labelGrid","id":"stable-id","left":60,"top":140,"width":880,"height":200,"rows":[{"header":"dimension","cells":["first","second"]}],"fontSize":16}. Native tables remain available and preferred for genuine tables.
Planned relationship component: {"type":"diagram","id":"stable-id","left":60,"top":140,"width":880,"height":330,"topology":"sequence|cycle|branch","nodes":[{"id":"a","label":"step"},{"id":"b","label":"next"}]}. Its rectangle and optional accentColor/nodeFill/textColor belong to your page design; the compiler supplies the exact planned nodes and edges. The planned annotation supplies explanatory evidence, not an obligation to repeat a full source paragraph inside the graph. Select a concise accurate annotation only if helpful, or display its needed meaning in nearby native text; include it explicitly as component.annotation and reserve measured space when selected. Do not draw duplicate diagram nodes/connectors in native elements.
Explicit branch edges, feedback, and sequenceGroups preserve the authoritative topology; independent sequences never gain cross-process connectors.
Arrows, connecting lines, aligned pairs and visual correspondence assert a real teaching relationship. Do not force introductory examples into a one-to-one mapping with concepts, or invent a correspondence, hierarchy or causal link not established by the supplied teaching design. If examples are only an introduction, present them as shared context without misleading connectors.
Components compile inside their allocated rectangles in this same first response. Background surfaces may deliberately contain foreground elements. Keep unrelated foreground content outside each component allocation. Include each required media resource as a native image/video in the page where it supports observation.`,
    user: outline.visualIntent?.diagram
      ? `Return native editable elements with exactly one local diagram component for this authoritative relationship: ${JSON.stringify(outline.visualIntent.diagram)}\nMeasured feasible diagram rectangles for complete node and edge labels, before an optional selected annotation: ${JSON.stringify(diagramAllocations)}. Choose one complete width/height pair or a rectangle at least as wide AND as high as one pair. A smaller arbitrary rectangle will not fit. You choose its left/top and the rest of the native page layout. Keep left >= 50, top >= 50, left+width <= 950 and top+height <= 512.5; reserve the page title and keep unrelated foreground content outside the chosen rectangle. The diagram is one local region, not the whole-page layout.`
      : 'Return native editable elements, with optional local text or label components only where helpful. Preserve the page composition and rich text styles.',
  };
}
