import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import type { AuthClaims } from "../src/lib/auth/session";
async function main() {
  const marker = process.env.OPENPBL_VERIFICATION_MARKER;
  assert.match(marker ?? "", /^openpbl-research-check-[0-9a-f-]{36}$/);
  const { prisma } = await import("../src/lib/db/client");
  try {
    const rows = await prisma.$queryRaw`SELECT marker FROM "_OpenpblVerification" WHERE marker = ${marker}`;
    assert.equal((rows as unknown[]).length, 1);
    const repo = await import("../src/lib/platform/repository");
    const { createPblTemplateCourse } = await import("../src/lib/platform/pbl-template");
    const { savePblTemplateCourse } = await import("../src/lib/platform/pbl-template-repository");
    const { executeCourseAction } = await import("../src/lib/courses/action-service");
    const { loadCourse } = await import("../src/lib/db/session-repository");
    const teacher = await prisma.user.create({ data: { username: "phase-teacher", usernameKey: "phase-teacher", displayName: "Phase teacher", role: "TEACHER", passwordHash: "unusable" } });
    const teacherClaims: AuthClaims = { sub: teacher.id, role: "teacher", displayName: teacher.displayName, username: teacher.username, sv: 1 };
    const design = createPblTemplateCourse(randomUUID(), { name: "Five stage verification" });
    await savePblTemplateCourse({ ...design, status: "ready" }, teacher.id);
    const version = await prisma.classroomTemplateVersion.findFirstOrThrow({ where: { templateId: design.id, status: "PUBLISHED" } });
    const offering = await repo.createOffering(teacherClaims, { name: "V2 phases" });
    await repo.updateOffering(teacherClaims, offering.id, { status: "OPEN" });
    const chapter = await repo.createChapter(teacherClaims, offering.id, { title: "Chapter" });
    await repo.updateChapter(teacherClaims, chapter.id, { isOpen: true });
    const activity = await repo.createActivity(teacherClaims, offering.id, chapter.id, { title: design.name, type: "Classroom", templateId: design.id });
    await repo.updateActivity(teacherClaims, activity.id, { isOpen: true });
    const instance = await prisma.classroomInstance.findFirstOrThrow({ where: { activityId: activity.id } });
    assert.equal(instance.templateVersionId, version.id);
    const config = { groupMode: "solo" as const, totalStudents: 24, perGroup: 1, crossClass: false };
    await executeCourseAction(instance.id, { requestId: randomUUID(), action: { type: "UPDATE_COURSE", payload: { id: instance.id, patch: { classConfig: config } } } }, teacherClaims);
    assert.equal((await loadCourse(instance.id))?.status, "ready");
    assert.equal((await loadCourse(instance.id))?.classConfig?.totalStudents, 24);
    assert.equal((await prisma.classroomInstance.findUniqueOrThrow({ where: { id: instance.id } })).startedAt, null);
    await executeCourseAction(instance.id, { requestId: randomUUID(), action: { type: "START_TEACHING", payload: { id: instance.id, classConfig: config, inviteCode: "UNUSED" } } }, teacherClaims);
    assert.equal(await prisma.domainEvent.count({ where: { classroomInstanceId: instance.id, eventType: "classroom_started" } }), 1);
    const invite = await repo.resetOfferingInvitation(teacherClaims, offering.id, {});
    const student = await repo.registerStudent({ invitationCode: invite.code, username: "phase-student", displayName: "Student", password: randomUUID() });
    const claims: AuthClaims = { sub: student.user.id, role: "student", studentName: "Student", sv: 1 };
    await repo.enterClassroom(claims, instance.id);
    const course = await loadCourse(instance.id);
    assert.ok(course); assert.equal(course.stages.length, 5); assert.equal(course.students[0].id, student.user.id);
    for (let index = 0; index < course.stages.length; index++) {
      await executeCourseAction(instance.id, { requestId: randomUUID(), action: { type: "SET_STAGE", payload: { id: instance.id, index } } }, teacherClaims);
      const stageKey = course.stages[index].key;
      await executeCourseAction(instance.id, { requestId: randomUUID(), action: { type: "UPDATE_STUDENT_PROGRESS", payload: { courseId: instance.id, studentId: student.user.id, stageKey, value: 100 } } }, claims);
      const now = new Date().toISOString();
      await executeCourseAction(instance.id, { requestId: randomUUID(), action: { type: "UPSERT_SUBMISSION", payload: { courseId: instance.id, submission: { id: randomUUID(), courseId: instance.id, studentId: student.user.id, studentName: "Student", stageKey, type: "document", title: stageKey, content: `Evidence for ${stageKey}`, createdAt: now, updatedAt: now, status: "submitted" } } } }, claims);
      const after = await loadCourse(instance.id);
      assert.equal(after?.currentStageIndex, index); assert.equal(after?.students[0].stageProgress[stageKey], 100);
      assert.ok(after?.submissions?.some(s => s.stageKey === stageKey && s.content === `Evidence for ${stageKey}`));
    }
    const now = new Date().toISOString();
    const reflectionId = randomUUID();
    await executeCourseAction(instance.id, { requestId: randomUUID(), action: { type: "UPSERT_REFLECTION", payload: { courseId: instance.id, reflection: { id: reflectionId, courseId: instance.id, studentId: student.user.id, studentName: "Student", content: "Reflection preserved", createdAt: now, updatedAt: now } } } }, claims);
    const reflected = await loadCourse(instance.id); assert.equal(reflected?.reflections?.[0].content, "Reflection preserved");
    const fact = await prisma.reflection.findUniqueOrThrow({ where: { id: reflectionId } }); assert.equal(fact.authorId, student.user.id);
    assert.equal(await prisma.classroomSubmission.count({ where: { participation: { instanceId: instance.id } } }), 5);
    assert.equal(await prisma.domainEvent.count({ where: { classroomInstanceId: instance.id, eventType: "COURSE_ACTION" } }), 18);
    await assert.rejects(() => executeCourseAction(instance.id, { requestId: randomUUID(), action: { type: "UPDATE_STUDENT_PROGRESS", payload: { courseId: instance.id, studentId: teacher.id, stageKey: "make", value: 100 } } }, claims));
    const beforeSnapshot = await prisma.classroomTemplateVersion.findUniqueOrThrow({ where: { id: version.id } });
    await executeCourseAction(instance.id, { requestId: randomUUID(), action: { type: "END_TEACHING", payload: { id: instance.id } } }, teacherClaims);
    const finished = await prisma.classroomInstance.findUniqueOrThrow({ where: { id: instance.id } });
    const participation = await prisma.classroomParticipation.findFirstOrThrow({ where: { instanceId: instance.id } });
    assert.equal(finished.status, "FINISHED"); assert.ok(finished.startedAt); assert.ok(finished.endedAt);
    assert.equal(participation.completedAt?.toISOString(), finished.endedAt.toISOString());
    assert.equal(await prisma.domainEvent.count({ where: { classroomInstanceId: instance.id, eventType: "classroom_finished" } }), 1);
    await assert.rejects(() => executeCourseAction(instance.id, { requestId: randomUUID(), action: { type: "UPDATE_STUDENT_PROGRESS", payload: { courseId: instance.id, studentId: student.user.id, stageKey: "make", value: 0 } } }, claims));
    await assert.rejects(() => repo.startClassroomInstance(teacherClaims, instance.id));
    const priorEntry = await prisma.classroomParticipation.findUniqueOrThrow({ where: { id: participation.id } });
    const priorEvents = await prisma.learningEvent.count({ where: { classroomInstanceId: instance.id } });
    await repo.enterClassroom(claims, instance.id);
    assert.deepEqual(await prisma.classroomParticipation.findUniqueOrThrow({ where: { id: participation.id } }), priorEntry);
    assert.equal(await prisma.learningEvent.count({ where: { classroomInstanceId: instance.id } }), priorEvents);
    const lateStudent = await repo.registerStudent({ invitationCode: invite.code, username: "phase-late-student", displayName: "Late student", password: randomUUID() });
    await assert.rejects(() => repo.enterClassroom({ sub: lateStudent.user.id, role: "student", studentName: "Late student", sv: 1 }, instance.id));
    const [newRun, sameRun] = await Promise.all([repo.createClassroomInstance(teacherClaims, activity.id, version.id), repo.createClassroomInstance(teacherClaims, activity.id, version.id)]);
    assert.notEqual(newRun.id, instance.id); assert.equal(newRun.id, sameRun.id); assert.equal(newRun.runNo, 2); assert.equal(newRun.status, "SCHEDULED");
    assert.equal(await prisma.classroomParticipation.count({ where: { instanceId: newRun.id } }), 0);
    assert.equal(await prisma.classroomSubmission.count({ where: { participation: { instanceId: instance.id } } }), 5);
    assert.deepEqual((await prisma.classroomTemplateVersion.findUniqueOrThrow({ where: { id: version.id } })).snapshot, beforeSnapshot.snapshot);
    console.log("PASS original workbench configuration/start/finish persistence, closed student writes, immutable history and concurrent new-run entry");

    const genericTemplate = await repo.createPrivateTemplate(teacherClaims, { title: "Compatible lesson", snapshot: { schemaVersion: 1, title: "Compatible lesson", subject: "Science", grade: "7", durationMinutes: 45, summary: "Read and create", learningObjectives: ["Analyze evidence"], outline: [{ title: "Investigation", durationMinutes: 45, description: "Explore community evidence" }], resources: [] } });
    const genericActivity = await repo.createActivity(teacherClaims, offering.id, chapter.id, { title: "Compatible lesson", type: "Classroom", templateId: genericTemplate.id });
    await repo.updateActivity(teacherClaims, genericActivity.id, { isOpen: true });
    const genericRun = await prisma.classroomInstance.findFirstOrThrow({ where: { activityId: genericActivity.id } });
    await repo.startClassroomInstance(teacherClaims, genericRun.id);
    const entered = await repo.enterClassroom(claims, genericRun.id);
    const { readClassroom } = await import("../src/lib/platform/classroom");
    assert.equal((await readClassroom(claims, entered.participation.id)).canWrite, true);
    await repo.finishClassroomInstance(teacherClaims, genericRun.id);
    assert.equal((await readClassroom(claims, entered.participation.id)).canWrite, false);
    assert.ok((await prisma.classroomParticipation.findUniqueOrThrow({ where: { id: entered.participation.id } })).completedAt);
    assert.equal(await prisma.domainEvent.count({ where: { classroomInstanceId: genericRun.id, eventType: { in: ["classroom_started", "classroom_finished"] } } }), 2);
    console.log("PASS non-PBL compatibility lifecycle, participation completion and read-only replay");
    const tables = await prisma.$queryRaw<Array<{ table_name: string }>>`SELECT table_name FROM information_schema.tables WHERE table_schema='public'`;
    assert.ok(!tables.some(t => ["Course", "Student", "Teacher", "CourseEvent"].includes(t.table_name)));
    console.log("PASS full five-stage teaching projection, normalized submissions/reflection, research receipts and student isolation without legacy tables");
  } finally { await prisma.$disconnect(); }
}
main().catch((error: unknown) => { console.error(error instanceof Error ? error.stack : "Five-stage verification failed"); process.exitCode = 1; });
